#!/bin/sh
echo "dameblanche has been moved to https://github.com/Prophets/dameblanche. Your local dameblanche installer will be updated"
curl -o /usr/local/bin/dameblanche https://raw.githubusercontent.com/Prophets/dameblanche/develop/bash/dameblanche &&  chmod 755 /usr/local/bin/dameblanche