#!/bin/bash

for ((i=1;i<=$#;i++)); 
do

    if [ ${!i} = "-create" ] 
    then ((i++)) 
        create=${!i};
    #example second argument
    #elif [ ${!i} = "-log" ];
    #then ((i++)) 
        #logFile=${!i};  
    fi
done;

#create a project directory if create parameter has been set
if [ ! -z "$create" ]
    then
        mkdir "$create"
        cd "$create"
fi

#clone the git project
git clone https://git.prophets.be/playground/lets-disagree-to-agree.git . 
# --> remove this when merged into master
git fetch origin
git checkout -t remotes/origin/13-prefix-commit-messages-with-branch-name
# <--- end remove
#
# remove dameblanch .git
rm -rf .git 
# initialize new .git
git init
# add commit message hook
cp git/hooks/prepare-commit-msg .git/hooks/prepare-commit-msg
# remove git (template hooks) and bash folder
rm -rf git
rm -rf bash
# create initial commit
git add -A 
git commit -m 'initial commit'

